### ISSUE TITLE
Unauthorized Access Issue

### ISSUE THREAD

**Issue by pratyush1712** [epicdragon44/hyperdti-cu#3]
Not to be nitpicky but people at AppDev are wilding with this site
<img width="358" alt="image" src="https://user-images.githubusercontent.com/80096811/233856356-05de5e79-1af8-4ce8-bd7c-4a583c35b16e.png">

Some tips that could help secure the site from other organizations lol:

- Password is hard coded and the repo is public: ahhhh
- I think it makes sense to password-protect the page where one adds the links
- Also, might not be a good way to simply blur the background as it still visible from the inspect elements tab
![image](https://user-images.githubusercontent.com/80096811/233856548-c0e264ff-1af6-4196-a1e6-d8e740b1ac2d.png)

**Comment by danielwei15** [comment]
appdev exhibiting peak fan behavior fr.

Honestly, I wasn't going to secure _any_ of this initially. None of it is particularly sensitive. Least of all the part where you enter the link -- that should be easily accessible. Websites like tinyurl.com, for instance, don't require protection to shorten a link.

The more stringent issue in the long term is protection against spam. Bot protection, perhaps by throttling requests over time, is a big issue. By comparison, a few AppDev members poses no real threat. 

The password was originally there for pure friction -- after all, the Hub used to be completely open for viewing. Now that we have beautiful things like antifans, I'll aim to protect the password via an env var though.

You raise good points overall.

**Roadmap**
- [ ] Bot protection
- [ ] Authentication for DTI members -- especially to view the Hub.
- [ ] Implement a better password gating mechanism (it's about as effective currently as those old NYT paywalls).
- [x] In the meantime, hide the password in an environment variable because lol.

**Comment by pratyush1712** [comment]
> appdev exhibiting peak fan behavior fr.
> 
> Honestly, I wasn't going to secure _any_ of this initially. None of it is particularly sensitive. Least of all the part where you enter the link -- that should be easily accessible. Websites like tinyurl.com, for instance, don't require protection to shorten a link.
> 
> The more stringent issue in the long term is protection against spam. Bot protection, perhaps by throttling requests over time, is a big issue. By comparison, a few AppDev members poses no real threat.
> 
> The password was originally there for pure friction -- after all, the Hub used to be completely open for viewing. Now that we have beautiful things like antifans, I'll aim to protect the password via an env var though.
> 
> You raise good points overall.
> 
> **Roadmap**
> 
> * [ ]  Bot protection
> * [ ]  Authentication for DTI members -- especially to view the Hub.
> * [ ]  Implement a better password gating mechanism (it's about as effective currently as those old NYT paywalls).
> * [x]  In the meantime, hide the password in an environment variable because lol.

Not sure if using env vars on frontend will help a lot because during build all env vars are unwrapped and the compiled code is available for anyone to see, so technically, anyone can look at the password from the website itself, but it's definitely better than nothing lol

**Comment by michelleli01** [comment]
> > appdev exhibiting peak fan behavior fr.
> > Honestly, I wasn't going to secure _any_ of this initially. None of it is particularly sensitive. Least of all the part where you enter the link -- that should be easily accessible. Websites like tinyurl.com, for instance, don't require protection to shorten a link.
> > The more stringent issue in the long term is protection against spam. Bot protection, perhaps by throttling requests over time, is a big issue. By comparison, a few AppDev members poses no real threat.
> > The password was originally there for pure friction -- after all, the Hub used to be completely open for viewing. Now that we have beautiful things like antifans, I'll aim to protect the password via an env var though.
> > You raise good points overall.
> > **Roadmap**
> > 
> > * [ ]   Bot protection
> > * [ ]   Authentication for DTI members -- especially to view the Hub.
> > * [ ]   Implement a better password gating mechanism (it's about as effective currently as those old NYT paywalls).
> > * [x]   In the meantime, hide the password in an environment variable because lol.
> 
> Not sure if using env vars on frontend will help a lot because during build all env vars are unwrapped and the compiled code is available for anyone to see, so technically, anyone can look at the password from the website itself, but it's definitely better than nothing lol

Yea it’s not a really viable solution, but we’re working on authentication and authorization now.

**Comment by danielwei15** [comment]
> > appdev exhibiting peak fan behavior fr.
> > Honestly, I wasn't going to secure _any_ of this initially. None of it is particularly sensitive. Least of all the part where you enter the link -- that should be easily accessible. Websites like tinyurl.com, for instance, don't require protection to shorten a link.
> > The more stringent issue in the long term is protection against spam. Bot protection, perhaps by throttling requests over time, is a big issue. By comparison, a few AppDev members poses no real threat.
> > The password was originally there for pure friction -- after all, the Hub used to be completely open for viewing. Now that we have beautiful things like antifans, I'll aim to protect the password via an env var though.
> > You raise good points overall.
> > **Roadmap**
> > 
> > * [ ]   Bot protection
> > * [ ]   Authentication for DTI members -- especially to view the Hub.
> > * [ ]   Implement a better password gating mechanism (it's about as effective currently as those old NYT paywalls).
> > * [x]   In the meantime, hide the password in an environment variable because lol.
> 
> Not sure if using env vars on frontend will help a lot because during build all env vars are unwrapped and the compiled code is available for anyone to see, so technically, anyone can look at the password from the website itself, but it's definitely better than nothing lol

I love this discussion!

As Michelle said, the final goal is proper authentication, obviously. An ambitious option I've been mulling -- implement SSO with something that DTI *does* tightly control (eg. NOT Cornell Google SSO, since AppDev members are also Cornell Google members). I'd propose a Github SSO, since we can easily check whether such a user is a member of the DTI organization.

Also, as for the env var, that's a good point. However, SvelteKit has [this](https://kit.svelte.dev/docs/modules#$env-dynamic-private) beautiful little module that lets me load the environment variable on the server-side code, and then send it to the client on page load. (https://kit.svelte.dev/docs/load) via a `+page.server.ts` file. I may be wrong, but that *should* prevent the data from unrolling client-side.

**Comment by danielwei15** [comment]
Don't want to be too public with the AppDev in the title.

**Comment by danielwei15** [comment]
Temporarily closing the Hub altogether ([d1ef5c4](https://github.com/cornell-dti/hyperdti-cu/commit/d1ef5c4309915be0bf567e823898b84eab243ddf)) until there's robust auth.

**Comment by danielwei15** [comment]
It does not look like there is a need for a link hub at all. Closing this for the foreseeable future.
